-- 011_create_blogs_table.sql
CREATE TABLE IF NOT EXISTS blogs (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    featured_image TEXT,
    short_description TEXT NOT NULL,
    content TEXT NOT NULL,
    category VARCHAR(100) NOT NULL,
    tags TEXT[],
    author VARCHAR(100) DEFAULT 'Yogkart Team',
    read_time VARCHAR(50) DEFAULT '7 min read',
    is_published BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    is_trending BOOLEAN DEFAULT false,
    meta_title VARCHAR(255),
    meta_description TEXT,
    keywords TEXT[],
    views_count INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Seed 20 Professional SEO-Friendly Organic Healthcare Blogs
INSERT INTO blogs (title, slug, featured_image, short_description, content, category, tags, author, read_time, is_published, is_featured, is_trending, meta_title, meta_description, keywords)
VALUES
(
    'Top 10 Benefits of Neem for Hair Growth',
    'top-10-benefits-of-neem-for-hair-growth',
    'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?q=80&w=800&auto=format&fit=crop',
    'Discover how pure neem wood and neem extracts boost scalp circulation, fight dandruff, and accelerate natural hair growth.',
    '<h2>Why Neem is Nature’s Greatest Gift for Hair</h2><p>Neem (Azadirachta indica) has been revered in Ayurvedic medicine for thousands of years. Packed with antibacterial, antifungal, and antioxidant properties, neem treats scalp infections, purifies roots, and promotes strong hair follicle growth.</p><h3>1. Clears Scalp Infections & Dandruff</h3><p>Malassezia fungus is a primary cause of stubborn dandruff. Neem contains nimbidin and nimbin which naturally destroy fungal spores without drying out natural scalp oils.</p><h3>2. Stimulates Follicle Blood Circulation</h3><p>Massaging scalp with neem oil or combing with a handcrafted neem wood comb stimulates blood flow directly to hair roots, supplying essential nutrient-rich oxygen.</p><h3>3. Prevents Premature Graying</h3><p>High levels of antioxidants in neem neutralize free radicals caused by environmental pollution and UV stress, protecting natural hair pigmentation.</p>',
    'Hair Care',
    ARRAY['Neem', 'Hair Growth', 'Scalp Care', 'Ayurveda'],
    'Yogkart Team',
    '6 min read',
    true, true, true,
    'Top 10 Benefits of Neem for Hair Growth | Yogkart Organic',
    'Learn how neem extracts and pure neem wood combs prevent hair fall, eliminate dandruff, and stimulate thick hair growth naturally.',
    ARRAY['neem for hair', 'hair growth remedies', 'ayurvedic hair care', 'neem wood comb']
),
(
    'Tea Tree Oil for Acne: Benefits & How to Use',
    'tea-tree-oil-for-acne-benefits-and-how-to-use',
    'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?q=80&w=800&auto=format&fit=crop',
    'A complete guide to using organic tea tree oil to heal active acne breakouts, reduce redness, and unclog facial pores safely.',
    '<h2>Understanding Tea Tree Oil for Clear Skin</h2><p>Tea tree oil is a powerful botanical extract known for its potent antimicrobial and anti-inflammatory compounds. Unlike harsh synthetic chemicals like benzoyl peroxide, tea tree oil kills acne-causing bacteria gently.</p><h3>How Terpinen-4-ol Fights Acne</h3><p>The key active compound in tea tree oil, Terpinen-4-ol, penetrates deep into clogged pores, soothing swollen blemishes and balancing excess sebum secretion.</p><h3>Best Way to Apply Tea Tree Oil</h3><p>Always dilute pure tea tree oil with a carrier oil like jojoba or aloe vera gel before applying directly onto active blemishes.</p>',
    'Skin Care',
    ARRAY['Tea Tree', 'Acne Treatment', 'Organic Skincare', 'Clear Skin'],
    'Yogkart Team',
    '7 min read',
    true, true, false,
    'Tea Tree Oil for Acne: Ultimate Guide | Yogkart Healthcare',
    'Discover how tea tree oil treats acne breakouts naturally, unclogs pores, and prevents post-acne scarring without harsh side effects.',
    ARRAY['tea tree oil acne', 'organic acne care', 'natural skincare', 'clear skin remedies']
),
(
    'Aloe Vera for Dry Skin: Complete Guide',
    'aloe-vera-for-dry-skin-complete-guide',
    'https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?q=80&w=800&auto=format&fit=crop',
    'Learn how 99% pure organic aloe vera gel locks in deep hydration, repairs skin barrier, and relieves dry flaky skin.',
    '<h2>The Science of Aloe Vera Hydration</h2><p>Aloe vera gel contains 99% water alongside polysaccharides, mucopolysaccharides, and essential vitamins A, C, and E. It creates a breathable moisture seal over sensitive dry skin.</p><h3>Restoring Damaged Skin Barrier</h3><p>Environment exposure damages skin lipids. Aloe vera stimulates fibroblast collagen production, repairing skin elasticity and preventing moisture loss.</p>',
    'Skin Care',
    ARRAY['Aloe Vera', 'Dry Skin', 'Hydration', 'Skin Barrier'],
    'Yogkart Team',
    '5 min read',
    true, false, true,
    'Aloe Vera for Dry Skin Guide | Deep Natural Hydration',
    'Explore how pure organic aloe vera gel locks in deep cellular hydration and restores dry, flaky skin without sticky residue.',
    ARRAY['aloe vera gel', 'dry skin hydration', 'organic skin repair', 'natural moisturizer']
),
(
    'Best Natural Remedies for Hair Fall',
    'best-natural-remedies-for-hair-fall',
    'https://images.unsplash.com/photo-1608248597263-0007999659b3?q=80&w=800&auto=format&fit=crop',
    'Stop excessive hair fall naturally with proven Ayurvedic herbs including Amla, Bhringraj, Onion Oil, and Kachi Neem.',
    '<h2>Root Causes of Hair Fall</h2><p>Excessive stress, poor nutrition, chemical shampoos, and hard water degrade hair follicle strength. Traditional herbs provide holistic root restoration.</p><h3>Top Herbal Remedies</h3><p><strong>Onion Oil:</strong> High in sulfur, boosting collagen for thick hair.<br><strong>Bhringraj:</strong> Known as the King of Herbs for hair regeneration.<br><strong>Neem Comb:</strong> Prevents static friction and scalp micro-tears.</p>',
    'Hair Care',
    ARRAY['Hair Fall', 'Amla', 'Bhringraj', 'Onion Oil', 'Ayurveda'],
    'Yogkart Team',
    '8 min read',
    true, true, true,
    'Best Natural Remedies for Hair Fall Control | Yogkart',
    'Stop hair shedding naturally with time-tested Ayurvedic hair oils, neem combs, and herbal hair care secrets.',
    ARRAY['hair fall remedies', 'ayurvedic hair oil', 'onion hair oil', 'natural hair care']
),
(
    'Why Chemical-Free Skincare is Better',
    'why-chemical-free-skincare-is-better',
    'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop',
    'Why switching to toxin-free, organic skincare protects your endocrine system, preserves collagen, and yields long-term radiant skin.',
    '<h2>The Hidden Dangers of Synthetic Skincare</h2><p>Conventional skincare products often contain parabens, sulfates (SLS), phthalates, and synthetic fragrances that penetrate skin pores into bloodstream.</p><h3>Long-Term Organic Benefits</h3><p>Organic formulations deliver active antioxidants directly into cells, enhancing natural repair mechanisms without systemic toxicity.</p>',
    'Wellness',
    ARRAY['Chemical Free', 'Organic Beauty', 'Clean Beauty', 'Skin Health'],
    'Yogkart Team',
    '6 min read',
    true, false, false,
    'Why Chemical-Free Skincare is Better | Clean Beauty Guide',
    'Learn why chemical-free organic skincare protects long-term health, preserves collagen, and leaves skin radiantly clear.',
    ARRAY['chemical free skincare', 'clean beauty products', 'organic face care']
),
(
    'Wooden Neem Comb Benefits for Healthy Hair',
    'wooden-neem-comb-benefits-for-healthy-hair',
    'https://images.unsplash.com/photo-1590159763121-7c9fd312190d?q=80&w=800&auto=format&fit=crop',
    'Ditch plastic combs! Discover how handcrafted Kachi Neem wooden combs distribute natural scalp oils, prevent breakage, and soothe scalp.',
    '<h2>Plastic vs Neem Wooden Comb</h2><p>Plastic combs produce electrostatic charge that weakens hair roots and causes frizz. Hand-carved Kachi Neem combs possess anti-static properties and release medicinal neem extracts with every stroke.</p>',
    'Hair Care',
    ARRAY['Neem Comb', 'Hair Breakage', 'Scalp Massage', 'Eco Friendly'],
    'Yogkart Team',
    '5 min read',
    true, true, true,
    'Wooden Neem Comb Benefits for Healthy Hair | Yogkart',
    'Discover why switching to a handcrafted neem wood comb stops hair breakage, distributes natural sebum, and soothes scalp.',
    ARRAY['neem comb benefits', 'kachi neem comb', 'wooden hair brush', 'hair fall control']
),
(
    'How to Build a Daily Skincare Routine Naturally',
    'how-to-build-a-daily-skincare-routine-naturally',
    'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    'Step-by-step 4-step organic skincare routine for morning and night using clean, natural botanicals tailored to your skin type.',
    '<h2>Step 1: Gentle Herbal Cleansing</h2><p>Start with a sulfate-free herbal cleanser containing Neem, Tea Tree, or Aloe Vera.</p><h2>Step 2: Hydrating Botanical Toner</h2><h2>Step 3: Nourishing Vitamin Serum</h2><h2>Step 4: Sun & Barrier Protection</h2>',
    'Skin Care',
    ARRAY['Skincare Routine', 'Natural Beauty', 'Morning Routine', 'Glow Skin'],
    'Yogkart Team',
    '9 min read',
    true, false, true,
    'How to Build a Daily Natural Skincare Routine | Yogkart',
    'Master the ultimate 4-step natural skincare routine for glowing, hydrated skin morning and night.',
    ARRAY['natural skincare routine', 'daily skin care steps', 'organic face routine']
),
(
    'Best Organic Face Wash for Oily Skin',
    'best-organic-face-wash-for-oily-skin',
    'https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=800&auto=format&fit=crop',
    'How to select an organic face cleanser that controls excess sebum, eliminates shine, and prevents clogged pores without stripping hydration.',
    '<h2>The Oily Skin Paradox</h2><p>Harsh cleansers strip natural skin moisture, causing sebaceous glands to overproduce sebum. Organic face washes balance skin pH gently.</p>',
    'Skin Care',
    ARRAY['Oily Skin', 'Face Wash', 'Sebum Control', 'Charcoal'],
    'Yogkart Team',
    '6 min read',
    true, false, false,
    'Best Organic Face Wash for Oily Skin | Sebum Control Guide',
    'Find the perfect herbal face cleanser for oily, acne-prone skin to control shine and keep pores deeply cleansed.',
    ARRAY['organic face wash oily skin', 'sebum control cleanser', 'herbal face wash']
),
(
    'Hair Care Routine During Monsoon',
    'hair-care-routine-during-monsoon',
    'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=800&auto=format&fit=crop',
    'Monsoon humidity causes severe frizz and scalp dampness. Learn essential tips to protect hair during rainy season.',
    '<h2>Beat Humidity & Frizz</h2><p>Rainwater acidity and high humidity invite fungal scalp issues. Use neem hair masks and light botanical oils to shield hair cuticles.</p>',
    'Hair Care',
    ARRAY['Monsoon Care', 'Frizz Control', 'Scalp Care', 'Hair Health'],
    'Yogkart Team',
    '7 min read',
    true, false, false,
    'Monsoon Hair Care Tips & Routine | Anti-Frizz Remedies',
    'Keep your hair frizz-free, strong, and healthy during humid monsoon months with natural botanical hair care.',
    ARRAY['monsoon hair care', 'frizz free hair remedies', 'rainy season hair routine']
),
(
    'Best Home Remedies for Dandruff',
    'best-home-remedies-for-dandruff',
    'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format&fit=crop',
    'Soothe flaky, itchy scalp naturally using neem, tea tree oil, apple cider vinegar, and aloe vera scalp treatments.',
    '<h2>Natural Anti-Dandruff Protocol</h2><p>Dandruff occurs when scalp microbiome becomes unbalanced. Botanical extracts restore healthy microflora without chemical residue.</p>',
    'Hair Care',
    ARRAY['Dandruff', 'Scalp Health', 'Neem', 'Tea Tree'],
    'Yogkart Team',
    '6 min read',
    true, true, false,
    'Best Home Remedies for Dandruff | Natural Scalp Care',
    'Eliminate scalp flaking and itchiness naturally with neem, tea tree oil, and aloe vera remedies.',
    ARRAY['dandruff home remedies', 'anti dandruff natural remedies', 'scalp itch treatment']
),
(
    'Vitamin C vs Niacinamide: Which is Better?',
    'vitamin-c-vs-niacinamide-which-is-better',
    'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    'Comparing Vitamin C and Niacinamide for hyperpigmentation, skin brightening, collagen boost, and pore tightening.',
    '<h2>Understanding the Actives</h2><p>Vitamin C is a master antioxidant that brightens dark spots. Niacinamide (Vitamin B3) strengthens skin barrier and reduces pore size.</p>',
    'Skin Care',
    ARRAY['Vitamin C', 'Niacinamide', 'Serums', 'Hyperpigmentation'],
    'Yogkart Team',
    '8 min read',
    true, true, false,
    'Vitamin C vs Niacinamide Comparison | Yogkart Guide',
    'Learn whether Vitamin C or Niacinamide serum is right for your skin type, brightening goals, and pore care.',
    ARRAY['vitamin c vs niacinamide', 'brightening serum guide', 'skin pigmentation care']
),
(
    'Sunscreen Myths You Should Stop Believing',
    'sunscreen-myths-you-should-stop-believing',
    'https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?q=80&w=800&auto=format&fit=crop',
    'Debunking common SPF myths! Learn why dark skin tones need sun protection and why mineral zinc sunscreen is safest.',
    '<h2>Myth 1: Dark Skin Does Not Need SPF</h2><p>UV radiation causes cellular photo-aging and hyperpigmentation across all melanin levels.</p>',
    'Skin Care',
    ARRAY['Sunscreen', 'SPF Myths', 'UV Protection', 'Mineral SPF'],
    'Yogkart Team',
    '6 min read',
    true, false, false,
    'Sunscreen Myths Debunked | Natural Mineral Sunscreen Guide',
    'Uncover top sunscreen myths and why natural mineral zinc oxide sunscreen provides safe broad-spectrum protection.',
    ARRAY['sunscreen myths', 'mineral sunscreen', 'spf protection tips']
),
(
    'Benefits of Charcoal for Deep Cleansing',
    'benefits-of-charcoal-for-deep-cleansing',
    'https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=800&auto=format&fit=crop',
    'Activated bamboo charcoal draws out micro-pollutants, excess oil, and impurities from deep skin pores.',
    '<h2>How Activated Charcoal Works</h2><p>Activated charcoal acts like a magnet, binding micro-particles of urban pollution, dust, and sebum without disrupting natural lipids.</p>',
    'Skin Care',
    ARRAY['Charcoal', 'Deep Cleansing', 'Detox', 'Pore Care'],
    'Yogkart Team',
    '5 min read',
    true, false, false,
    'Benefits of Charcoal for Deep Skin Cleansing | Yogkart',
    'Learn how activated bamboo charcoal purifies pores, removes urban pollution, and prevents blackheads naturally.',
    ARRAY['charcoal skin benefits', 'deep pore cleanser', 'detox face wash']
),
(
    'How to Choose Organic Personal Care Products',
    'how-to-choose-organic-personal-care-products',
    'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop',
    'A beginner guide to reading ingredient labels, recognizing greenwashing, and picking certified organic body & hair care.',
    '<h2>Decode Greenwashing Labels</h2><p>Look beyond "Natural" marketing claims. Verify actual ingredient lists for absence of parabens, SLS, and artificial colorants.</p>',
    'Wellness',
    ARRAY['Organic Certification', 'Clean Label', 'Personal Care'],
    'Yogkart Team',
    '7 min read',
    true, false, false,
    'How to Choose Authentic Organic Personal Care Products',
    'Learn how to read cosmetics labels and select truly clean, chemical-free personal care items for your family.',
    ARRAY['choose organic skincare', 'read cosmetic labels', 'greenwashing guide']
),
(
    'Natural Ingredients That Actually Work',
    'natural-ingredients-that-actually-work',
    'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?q=80&w=800&auto=format&fit=crop',
    'Scientific breakdown of 5 clinically backed botanical ingredients: Neem, Turmeric, Gotu Kola, Amla, and Saffron.',
    '<h2>Clinically Proven Botanicals</h2><p>Modern research confirms ancient Ayurvedic wisdom. Saffron reduces melanin production; Amla provides potent Vitamin C collagen stimulation.</p>',
    'Wellness',
    ARRAY['Botanicals', 'Active Ingredients', 'Ayurvedic Science'],
    'Yogkart Team',
    '9 min read',
    true, false, true,
    'Natural Ingredients That Work | Science of Herbal Beauty',
    'Explore the scientific proof behind top Ayurvedic botanicals like Neem, Amla, Saffron, and Aloe Vera.',
    ARRAY['proven natural ingredients', 'ayurvedic botanicals science', 'herbal actives']
),
(
    'Ayurvedic Hair Care Tips',
    'ayurvedic-hair-care-tips',
    'https://images.unsplash.com/photo-1608248597263-0007999659b3?q=80&w=800&auto=format&fit=crop',
    'Ancient Ayurvedic rituals for luscious, thick hair: Warm oil scalp massage (Shiro Abhyanga), herbal rinsing, and neem combing.',
    '<h2>The Art of Shiro Abhyanga</h2><p>Weekly warm herbal oil scalp massage calms the nervous system, balances Vata/Pitta doshas, and nourishes hair roots deeply.</p>',
    'Hair Care',
    ARRAY['Ayurveda', 'Hair Care Tips', 'Shiro Abhyanga', 'Herbal Oils'],
    'Yogkart Team',
    '8 min read',
    true, true, false,
    'Ayurvedic Hair Care Tips for Thick Healthy Hair | Yogkart',
    'Transform hair texture and strength with ancient Ayurvedic hair care rituals and organic herbal scalp oils.',
    ARRAY['ayurvedic hair care tips', 'shiro abhyanga hair oil', 'herbal hair growth']
),
(
    'How to Reduce Hair Fall Naturally',
    'how-to-reduce-hair-fall-naturally',
    'https://images.unsplash.com/photo-1590159763121-7c9fd312190d?q=80&w=800&auto=format&fit=crop',
    'Actionable steps to stop hair shedding: Dietary nutrition, stress control, wooden neem comb routine, and sulfate-free washing.',
    '<h2>Holistic Hair Loss Reduction</h2><p>Combining internal protein & iron intake with external neem wooden combing minimizes mechanical traction breakage.</p>',
    'Hair Care',
    ARRAY['Hair Fall Reduction', 'Neem Comb', 'Hair Strength'],
    'Yogkart Team',
    '6 min read',
    true, false, true,
    'How to Reduce Hair Fall Naturally | Yogkart Action Guide',
    'Actionable holistic guide to halt hair loss, strengthen roots, and promote dense hair growth naturally.',
    ARRAY['reduce hair fall naturally', 'stop hair shedding', 'natural hair remedies']
),
(
    'Best Skin Care Tips for Summer',
    'best-skin-care-tips-for-summer',
    'https://images.unsplash.com/photo-1526947425960-945c6e72858f?q=80&w=800&auto=format&fit=crop',
    'Protect your skin from summer heat, sun tanning, and clogged sweat pores using lightweight aloe vera, cucumber, and SPF.',
    '<h2>Summer Skin Strategy</h2><p>Switch heavy winter creams for fast-absorbing hydration gels like pure aloe vera and rosewater botanical toners.</p>',
    'Skin Care',
    ARRAY['Summer Skincare', 'Sun Protection', 'Aloe Vera', 'Tanning'],
    'Yogkart Team',
    '5 min read',
    true, false, false,
    'Best Summer Skincare Tips & Routine | Yogkart Healthcare',
    'Keep skin cool, hydrated, and protected from sun tan during hot summer months with organic aloe remedies.',
    ARRAY['summer skincare tips', 'sun tan removal', 'aloe vera summer care']
),
(
    'Organic vs Chemical Beauty Products',
    'organic-vs-chemical-beauty-products',
    'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop',
    'Head-to-head comparison of organic botanical beauty formulations vs synthetic chemical products in terms of safety, effectiveness, and environment.',
    '<h2>In-Depth Comparison</h2><p>Chemical products offer quick temporary fixes but damage skin barrier over time. Organic products nourish skin cells for lasting vitality.</p>',
    'Wellness',
    ARRAY['Organic vs Chemical', 'Beauty Products', 'Skin Safety'],
    'Yogkart Team',
    '7 min read',
    true, false, false,
    'Organic vs Chemical Beauty Products | Comprehensive Guide',
    'Understand key differences between organic plant formulations and chemical beauty items for long-term health.',
    ARRAY['organic vs chemical beauty', 'clean cosmetics comparison', 'skincare safety']
),
(
    'Why Switch to Herbal Personal Care Products',
    'why-switch-to-herbal-personal-care-products',
    'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?q=80&w=800&auto=format&fit=crop',
    'Make the healthy transition to herbal soaps, neem wooden combs, natural shampoos, and toxin-free body care today.',
    '<h2>Your Journey to Herbal Wellness</h2><p>Switching to herbal personal care reduces your daily chemical exposure by over 80%, promoting overall body wellness and environmental sustainability.</p>',
    'Wellness',
    ARRAY['Herbal Products', 'Eco Wellness', 'Switch to Herbal'],
    'Yogkart Team',
    '6 min read',
    true, true, true,
    'Why Switch to Herbal Personal Care Products | Yogkart',
    'Start your transition to herbal personal care for safer skin, healthier hair, and an eco-friendly lifestyle.',
    ARRAY['switch to herbal care', 'herbal personal care products', 'eco clean wellness']
)
ON CONFLICT (slug) DO NOTHING;
